//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRental
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoices
    {
        public decimal id { get; set; }
        public decimal rent_id { get; set; }
        public decimal price { get; set; }
        public System.DateTime date { get; set; }
    
        public virtual Rents Rents { get; set; }
    }
}
